apiVersion: v1
kind: Service
metadata:
  name: gradio-service
spec:
  selector:
    app: gradio
  ports:
    - protocol: TCP
      port: 7860        # port widoczny w Kubernetes
      targetPort: 7860  # port w kontenerze
  type: NodePort