apiVersion: v1
kind: Pod
metadata:
  name: gradio-pod
  labels:
    app: gradio
spec:
  containers:
    - name: gradio
      image: gradio-k8s-demo:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 7860